# Site settings
title: Always Be Learning
email: britney@britneywright.com
description: "The technical blog of Britney Wright. Emphasis on Ruby, Ruby on Rails and front-end development. Also other things, because I said so."
baseurl: ""
url: "http://alwaysbelearning.co"
username: britneywright

# Build settings
markdown: kramdown
permalink: pretty
